version: '3'
services:
    zookeeper-1: 
        image: ${REPOSITORY}/cp-zookeeper:latest
        container_name: zookeeper-1
        ports:
          - 22181:2181
        environment:
          ZOOKEEPER_SERVER_ID: 1
          ZOOKEEPER_CLIENT_PORT: 2181
          ZOOKEEPER_TICK_TIME: 2000
          ZOOKEEPER_SERVERS: zookeeper-1:2888:3888;zookeeper-2:2888:3888;zookeeper-3:2888:3888
#          ZOOKEEPER_AUTH_PROVIDER_SASL: org.apache.zookeeper.server.auth.SASLAuthenticationProvider
#          ZOOKEEPER_SASL_ENABLED : 'false'
#          ZOOKEEPER_AUTH_PROVIDER_SASL: org.apache.zookeeper.server.auth.SASLAuthenticationProvider
        volumes:
          - ./config/zookeeper_jaas.conf:/etc/kafka/zookeeper_jaas.conf
#
    zookeeper-2: 
        image: ${REPOSITORY}/cp-zookeeper:latest
        container_name: zookeeper-2
        depends_on:
          - zookeeper-1
        ports:
          - 32181:2181
        environment:
          ZOOKEEPER_SERVER_ID: 2
          ZOOKEEPER_CLIENT_PORT: 2181
          ZOOKEEPER_TICK_TIME: 2000
          ZOOKEEPER_SERVERS: zookeeper-1:2888:3888;zookeeper-2:2888:3888;zookeeper-3:2888:3888
#
#          ZOOKEEPER_AUTH_PROVIDER_SASL: org.apache.zookeeper.server.auth.SASLAuthenticationProvider
#          ZOOKEEPER_SASL_ENABLED : 'false'
#          ZOOKEEPER_AUTH_PROVIDER_SASL: org.apache.zookeeper.server.auth.SASLAuthenticationProvider
        volumes:
          - ./config/zookeeper_jaas.conf:/etc/kafka/zookeeper_jaas.conf
#
    zookeeper-3: 
        image: ${REPOSITORY}/cp-zookeeper:latest
        container_name: zookeeper-3
        depends_on:
          - zookeeper-1
          - zookeeper-2
        ports:
          - 42181:2181
        environment:
          ZOOKEEPER_SERVER_ID: 3
          ZOOKEEPER_CLIENT_PORT: 2181
          ZOOKEEPER_TICK_TIME: 2000
          ZOOKEEPER_SERVERS: zookeeper-1:2888:3888;zookeeper-2:2888:3888;zookeeper-3:2888:3888
#
#          ZOOKEEPER_AUTH_PROVIDER_SASL: org.apache.zookeeper.server.auth.SASLAuthenticationProvider
#          ZOOKEEPER_SASL_ENABLED : 'false'
#          ZOOKEEPER_AUTH_PROVIDER_SASL: org.apache.zookeeper.server.auth.SASLAuthenticationProvider
        volumes:
          - ./config/zookeeper_jaas.conf:/etc/kafka/zookeeper_jaas.conf
#
    kafka-1:
        image: ${REPOSITORY}/cp-enterprise-kafka:latest
        container_name: kafka-1
        ports:
#          - 9092
#          - 9093
          - 29991:9991
          - 29992:9992
          - 29092:9092
          - 29093:9093
          - 29094:9094
          - 29010:9010
        depends_on:
          - zookeeper-1
          - zookeeper-2
          - zookeeper-3
        environment:
          KAFKA_BROKER_ID: 1
          KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
          KAFKA_ZOOKEEPER_SSL_CLIENT_ENABLE: 'false'
          #
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: SASL_PLAINTEXT:SASL_PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT,EXTERNAL_SASL_PLAINTEXT:SASL_PLAINTEXT
          KAFKA_LISTENERS: PLAINTEXT://kafka-1:9092,SASL_PLAINTEXT://kafka-1:9093,EXTERNAL_SASL_PLAINTEXT://kafka-1:9094
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092,SASL_PLAINTEXT://kafka-1:9093,EXTERNAL_SASL_PLAINTEXT://127.0.0.1:29094
          KAFKA_INTERNAL_BROKER_LISTENER_NAME: SASL_PLAINTEXT
          #
          KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: SCRAM-SHA-256
          KAFKA_SASL_ENABLED_MECHANISMS: SCRAM-SHA-256
          KAFKA_SUPER_USERS: User:admin
          KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: 'true'
          #
          #KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.auth.SimpleAclAuthorizer
          #KAFKA_AUTHORIZER_CLASS_NAME: io.confluent.kafka.security.authorizer.ConfluentServerAuthorizer
          #
          #KAFKA_JMX_OPTS: "-Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.port=9991 -Dcom.sun.management.jmxremote.rmi.port=9992"
          #JMX_PORT: 9991
          # KAFKA_JMX_PORT: 9991
          EXTRA_ARGS: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false \
          -Dcom.sun.management.jmxremote.ssl=false -Djava.util.logging.config.file=logging.properties \
          -javaagent:/usr/share/jmx_exporter/jmx_prometheus_javaagent-0.17.0.jar=9010:/usr/share/jmx_exporter/config.yml"

          #EXTRA_ARGS: "-javaagent:/usr/share/jmx_exporter/jmx_prometheus_javaagent-0.17.0.jar=9010:/usr/share/jmx_exporter/kafka-broker.yaml" 
          #
          ZOOKEEPER_SASL_ENABLED : 'false'
          #KAFKA_OPTS: "-Dzookeeper.sasl.client=true -Dzookeeper.sasl.clientconfig=Client -Djava.security.auth.login.config=/etc/config/kafka_server_jaas.conf"
          KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/config/kafka_server_jaas.conf"
        volumes:
         - ./config/:/etc/config/
         - ./monitoring/:/usr/share/jmx_exporter/
#    
    kafka-2:
        image: ${REPOSITORY}/cp-enterprise-kafka:latest
        container_name: kafka-2
        ports:
#          - 9092
#          - 9093
          - 39992:9991
          - 39092:9092
          - 39093:9093
          - 39094:9094
          - 39010:9010
        depends_on:
          - zookeeper-1
          - zookeeper-2
          - zookeeper-3
          - kafka-1
        environment:
          KAFKA_BROKER_ID: 2
          KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
          KAFKA_ZOOKEEPER_SSL_CLIENT_ENABLE: 'false'
          #
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: SASL_PLAINTEXT:SASL_PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT,EXTERNAL_SASL_PLAINTEXT:SASL_PLAINTEXT
          KAFKA_LISTENERS: PLAINTEXT://kafka-2:9092,SASL_PLAINTEXT://kafka-2:9093,EXTERNAL_SASL_PLAINTEXT://kafka-2:9094
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:9092,SASL_PLAINTEXT://kafka-2:9093,EXTERNAL_SASL_PLAINTEXT://127.0.0.1:39094
          KAFKA_INTERNAL_BROKER_LISTENER_NAME: SASL_PLAINTEXT
          #
          KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: SCRAM-SHA-256
          KAFKA_SASL_ENABLED_MECHANISMS: SCRAM-SHA-256
          KAFKA_SUPER_USERS: User:admin
          KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: 'true'
          #
          #KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.auth.SimpleAclAuthorizer
          #KAFKA_AUTHORIZER_CLASS_NAME: io.confluent.kafka.security.authorizer.ConfluentServerAuthorizer
          #
          #KAFKA_JMX_OPTS: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=172.18.0.6 -Dcom.sun.management.jmxremote.rmi.port=9991"
          #KAFKA_JMX_PORT: 9991
          EXTRA_ARGS: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false \
              -Dcom.sun.management.jmxremote.ssl=false -Djava.util.logging.config.file=logging.properties \
              -javaagent:/usr/share/jmx_exporter/jmx_prometheus_javaagent-0.17.0.jar=9010:/usr/share/jmx_exporter/config.yml"
          #
          ZOOKEEPER_SASL_ENABLED : 'false'
          #KAFKA_OPTS: "-Dzookeeper.sasl.client=true -Dzookeeper.sasl.clientconfig=Client -Djava.security.auth.login.config=/etc/config/kafka_server_jaas.conf"
          KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/config/kafka_server_jaas.conf"
        volumes:
          - ./config/:/etc/config/
          - ./monitoring/:/usr/share/jmx_exporter/
#
    kafka-3:
        image: ${REPOSITORY}/cp-enterprise-kafka:latest
        container_name: kafka-3
        ports:
#          - 9092
#          - 9093
          - 49991:9991
          - 49092:9092
          - 49093:9093
          - 49094:9094
          - 49010:9010
        depends_on:
          - zookeeper-1
          - zookeeper-2
          - zookeeper-3
          - kafka-1
          - kafka-2
        environment:
          KAFKA_BROKER_ID: 3
          KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
          KAFKA_ZOOKEEPER_SSL_CLIENT_ENABLE: 'false'
          #
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: SASL_PLAINTEXT:SASL_PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT,EXTERNAL_SASL_PLAINTEXT:SASL_PLAINTEXT
          KAFKA_LISTENERS: PLAINTEXT://kafka-3:9092,SASL_PLAINTEXT://kafka-3:9093,EXTERNAL_SASL_PLAINTEXT://kafka-3:9094
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-3:9092,SASL_PLAINTEXT://kafka-3:9093,EXTERNAL_SASL_PLAINTEXT://127.0.0.1:49094          
          KAFKA_INTERNAL_BROKER_LISTENER_NAME: SASL_PLAINTEXT
          #
          KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: SCRAM-SHA-256
          KAFKA_SASL_ENABLED_MECHANISMS: SCRAM-SHA-256
          KAFKA_SUPER_USERS: User:admin
          KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: 'true'
          #
          #KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.auth.SimpleAclAuthorizer
          #KAFKA_AUTHORIZER_CLASS_NAME: io.confluent.kafka.security.authorizer.ConfluentServerAuthorizer
          #
          #KAFKA_JMX_OPTS: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=172.18.0.7 -Dcom.sun.management.jmxremote.rmi.port=9991"
          #KAFKA_JMX_PORT: 9991
          EXTRA_ARGS: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false \
              -Dcom.sun.management.jmxremote.ssl=false -Djava.util.logging.config.file=logging.properties \
               -javaagent:/usr/share/jmx_exporter/jmx_prometheus_javaagent-0.17.0.jar=9010:/usr/share/jmx_exporter/config.yml"
          #
          ZOOKEEPER_SASL_ENABLED : 'false'
          #KAFKA_OPTS: "-Dzookeeper.sasl.client=true -Dzookeeper.sasl.clientconfig=Client -Djava.security.auth.login.config=/etc/config/kafka_server_jaas.conf"
          KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/config/kafka_server_jaas.conf"
        volumes:
          - ./config/:/etc/config/
          - ./monitoring/:/usr/share/jmx_exporter/
#        